### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by jepunband** [Reptilian221/Email-Spammer#2]
python3 app.py <email-address>

Traceback (most recent call last):
  File "/home/user/Email-Spammer/app.py", line 56, in <module>
    spam1()
  File "/home/user/Email-Spammer/app.py", line 48, in spam1
    tarayici.open(link)
  File "/usr/lib/python3/dist-packages/mechanize/_mechanize.py", line 257, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/lib/python3/dist-packages/mechanize/_mechanize.py", line 313, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 403: b'request disallowed by robots.txt'

**Comment by Reptilian221** [comment]
Hello App is no longer supported :(
